package wizard

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/distance1186/jobber/cli/internal/detect"
	"github.com/distance1186/jobber/cli/internal/recommend"
)

//go:embed static/*
var staticFiles embed.FS

// Serve starts the config wizard web server and opens the browser.
func Serve(projectDir string, hw detect.HardwareInfo) error {
	mux := http.NewServeMux()

	// Serve static files
	sub, err := fs.Sub(staticFiles, "static")
	if err != nil {
		return fmt.Errorf("failed to load static files: %w", err)
	}
	mux.Handle("/", http.FileServer(http.FS(sub)))

	// API: hardware info + model recommendation
	mux.HandleFunc("/api/hardware", func(w http.ResponseWriter, r *http.Request) {
		rec := recommend.ForHardware(hw)
		resp := map[string]any{
			"hardware":       hw,
			"recommendation": rec,
			"all_models":     recommend.AllModels,
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	})

	// API: save configuration and start stack
	mux.HandleFunc("/api/save", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "POST only", http.StatusMethodNotAllowed)
			return
		}
		var config struct {
			PostgresPassword string `json:"postgres_password"`
			OllamaModel      string `json:"ollama_model"`
			LiAtCookie        string `json:"li_at_cookie"`
			NotifyURLs        string `json:"notify_urls"`
			NotifyMinScore    string `json:"notify_min_score"`
		}
		if err := json.NewDecoder(r.Body).Decode(&config); err != nil {
			http.Error(w, "invalid JSON", http.StatusBadRequest)
			return
		}

		// Write .env file
		envPath := filepath.Join(projectDir, ".env")
		if err := writeEnvFile(envPath, config.PostgresPassword, config.OllamaModel,
			config.LiAtCookie, config.NotifyURLs, config.NotifyMinScore, hw); err != nil {
			http.Error(w, fmt.Sprintf("failed to write .env: %v", err), http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok", "env_path": envPath})
	})

	// API: start the docker compose stack
	mux.HandleFunc("/api/start", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "POST only", http.StatusMethodNotAllowed)
			return
		}
		composePath := filepath.Join(projectDir, "docker-compose.yml")
		cmd := exec.Command("docker", "compose", "-f", composePath, "up", "-d", "--build")
		cmd.Dir = projectDir
		output, err := cmd.CombinedOutput()
		if err != nil {
			http.Error(w, fmt.Sprintf("docker compose failed: %s\n%s", err, output), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok", "output": string(output)})
	})

	// API: shutdown the wizard server
	srv := &http.Server{Addr: ":9898", Handler: mux}
	mux.HandleFunc("/api/done", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "bye"})
		go func() {
			time.Sleep(500 * time.Millisecond)
			srv.Shutdown(context.Background())
		}()
	})

	// Open browser
	go func() {
		time.Sleep(500 * time.Millisecond)
		openBrowser("http://localhost:9898")
	}()

	fmt.Println("  Config wizard running at http://localhost:9898")
	fmt.Println("  Press Ctrl+C to cancel, or complete the wizard in your browser.")
	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
		return err
	}
	fmt.Println("  ✓ Configuration complete!")
	return nil
}

func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "linux":
		cmd = exec.Command("xdg-open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	case "darwin":
		cmd = exec.Command("open", url)
	}
	if cmd != nil {
		cmd.Start()
	}
}

func writeEnvFile(path, pgPass, model, liAt, notifyURLs, notifyMin string, hw detect.HardwareInfo) error {
	ollamaURL := "http://ollama:11434"
	if hw.OS == "windows" {
		ollamaURL = "http://host.docker.internal:11434"
	}

	lines := []string{
		"# Generated by jobber-setup",
		"# ── Database ──────────────────────────────────────────",
		"POSTGRES_USER=jobtracker",
		fmt.Sprintf("POSTGRES_PASSWORD=%s", pgPass),
		"POSTGRES_DB=jobtracking",
		"",
		"# ── Ollama LLM ────────────────────────────────────────",
		fmt.Sprintf("OLLAMA_MODEL=%s", model),
		fmt.Sprintf("OLLAMA_BASE_URL=%s", ollamaURL),
		"",
		"# ── LinkedIn Authentication ───────────────────────────",
		fmt.Sprintf("LI_AT_COOKIE=%s", liAt),
		"",
		"# ── Dashboard ─────────────────────────────────────────",
		"NEXTAUTH_SECRET=" + generateSecret(),
		"NEXTAUTH_URL=http://localhost:3000",
		"",
		"# ── Notifications ─────────────────────────────────────",
		fmt.Sprintf("NOTIFY_URLS=%s", notifyURLs),
		fmt.Sprintf("NOTIFY_MIN_SCORE=%s", notifyMin),
		"",
		"# ── Scraper Schedule ──────────────────────────────────",
		"SCRAPE_SCHEDULE=0 7,12,18 * * *",
	}

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func generateSecret() string {
	out, err := exec.Command("openssl", "rand", "-base64", "32").Output()
	if err != nil {
		return "change-me-generate-with-openssl"
	}
	return strings.TrimSpace(string(out))
}
